language: python
group: travis_latest

dist: xenial

services:
  - docker
cache: pip

matrix:
  include:
  - os: osx
    language: sh
    python: '3.7'
    before_install:
    - pip3 install mock
    script:
    - python3 -m pytest --log-format='%(asctime)s.%(msecs)03d %(filename)-25s %(lineno)4d %(levelname)-8s %(message)s' --log-date-format='%Y-%m-%d %H:%M:%S' --log-level debug
  - os: windows
    language: sh
    python: '3.7'
    before_install:
    - choco install python --version 3.7.4
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    - python -m pip install --upgrade pip wheel
    - python -m pip install mock
  - os: linux
    python: '3.6'
  - os: linux
    python: '3.7'
    after_success:
       - codecov --token=dbadb6ba-0032-4812-bcc2-67ef7bafdfed
    deploy:
      - provider: pypi
        user: gilesknap
        password:
          secure: "fSs+RHlTlbT0KqOUKB9leEfIyeMz/4l/BdAaxbwiSlg0ruz5A/zmJMsO642s1MV4/Mc8Ng/2M/+Pkm7hkPea2trFEUZCuC+w0e0pi56mbit/ntqMYMFdYGyfERo1VRKA41Jvbcg7pOHQCF+DymUun/ApKb4V0I2dv5bJpmMlBLEq/2UEALciBRZAROklBBNEo5KFOLVZhRw/XdurCVVsQGKmORg543Bqepb3DBz4Nv/QfPKgq/U4nCoPwA6JSWAE0HJaKz7z6zkifrf6d9OlwGCm9RVwmdsmLSpEJK01NKYU4er3kVaQGmDytDGk542nHrOF8V+IT2M3MVtKFzq+gKNRXUD1Ghfytt/1rhCRFqX7Taqh1j3ivHp2lp/tBVNwXw04vD0aXQk8lyZaIzy9m/C+ioCmNUvVoerGHDdmR6bJ/OsS2Dd4P3wmsqLQ6nJLn8S3jZsTy2gTtacYoTgmyZtbRhlbAsOc/ZEwHQwJbiDfBacwfRVD5JaXLYuff1JJ5mqwK1iC31oqLoxu4JDSEQ/ihpE7SVVn2qe47XYs/Z++6kVe6qfbYQ6aSwajgaHeA8sNiapvEsV0/Cocm/Th7nsUfUMqVrP3mcoNPs3NH1ITTcKU/o6CxOX7HQainz/WbRtHVNObHSz1mhad9fx8foDA+Hs+j9ntWvwnTpkE3jE="
        on:
          tags: true
        distributions: "sdist bdist_wheel"
      - provider: script
        script: bash ./build-docker.sh
        on:
          tags: true

install:
- pip3 install .
- pip3 install codecov
- pip3 install pytest
- pip3 install pytest-cov
script:
- python -m pytest --cov=gphotos --log-format='%(asctime)s.%(msecs)03d %(filename)-25s
  %(lineno)4d %(levelname)-8s %(message)s' --log-date-format='%Y-%m-%d %H:%M:%S' --log-level
  debug
