language: python
matrix:
  include:
    - python: 3.6.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov

# command to run tests
script:
 - pytest --cov=gphotos

# submit coverage
after_script:
 - coveralls
